"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import type {Attachment,Conversation,Message} from "@/lib/aura-types";
import {checked,saveConversation,streamReply} from "@/services/chat";
export function useAuraChat(){const [conversations,setConversations]=useState<Conversation[]>([]);const [current,setCurrent]=useState<Conversation|null>(null);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [signedIn,setSignedIn]=useState(true);const [mode,setMode]=useState<"demo"|"live">("demo");const controller=useRef<AbortController|null>(null);const busyRef=useRef(false);const currentRef=useRef(current);currentRef.current=current;
const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/conversations");if(r.status===401){setSignedIn(false);return}const data=await (await checked(r)).json();setConversations(data.conversations);setSignedIn(true);setError("")}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
useEffect(()=>{void load();fetch("/api/status").then(r=>r.json()).then(d=>setMode(d.mode)).catch(()=>{});return()=>controller.current?.abort()},[load]);
const update=(c:Conversation)=>{setCurrent({...c,messages:[...c.messages]});setConversations(all=>[c,...all.filter(x=>x.id!==c.id)])};
const send=async(text:string,attachments:Attachment[]=[])=>{if(busyRef.current||(!text.trim()&&!attachments.length))return "";if(!signedIn){setError("Entre com sua conta para conversar e salvar o histórico.");return ""}if((currentRef.current?.messages.length||0)>=78){setError("Esta conversa atingiu o limite. Comece uma nova conversa.");return ""}busyRef.current=true;setBusy(true);setError("");const user:Message={id:crypto.randomUUID(),role:"user",content:text.trim(),attachments};const c:Conversation=currentRef.current?{...currentRef.current,messages:[...currentRef.current.messages,user],updated:Date.now()}:{id:crypto.randomUUID(),title:(text.trim()||attachments[0]?.name||"Nova conversa").slice(0,80),messages:[user],updated:Date.now()};const abort=new AbortController();controller.current=abort;let answer="";update(c);
try{await saveConversation(c);if(abort.signal.aborted)return "";const context=[...c.messages];const assistant:Message={id:crypto.randomUUID(),role:"assistant",content:""};c.messages.push(assistant);update(c);await streamReply(context,abort.signal,delta=>{answer+=delta;assistant.content=answer;update(c)})}catch(e){if(!abort.signal.aborted)setError((e as Error).message)}finally{c.messages=c.messages.filter(m=>m.role==="user"||m.content);update(c);try{await saveConversation(c)}catch{setError("A conversa permanece nesta tela, mas não foi salva. Use Salvar novamente antes de sair.")}busyRef.current=false;setBusy(false);controller.current=null}return answer};
const retrySave=async()=>{if(!current)return;try{await saveConversation(current);setError("")}catch(e){setError((e as Error).message)}};
return {conversations,current,busy,loading,error,setError,signedIn,mode,send,load,retrySave,stop:()=>controller.current?.abort(),newConversation:()=>{if(!busyRef.current){setCurrent(null);setError("")}},select:(c:Conversation)=>{if(!busyRef.current){setCurrent(c);setError("")}},remove:async(id:string)=>{try{await checked(await fetch(`/api/conversations?id=${encodeURIComponent(id)}`,{method:"DELETE"}));setConversations(all=>all.filter(c=>c.id!==id));if(current?.id===id)setCurrent(null)}catch(e){setError((e as Error).message)}}};
}
