"use client";
import {useEffect,useState} from "react";
import {ArrowUpRight,ArrowDown,ArrowRight,AudioLines,Plus} from "lucide-react";
import AuraCore from "./AuraCore";
const chapters=["Nascimento","Conversa","Voz","Possibilidades","Seu próximo passo"];
export default function Landing({onEnter}:{onEnter:()=>void}){const [step,setStep]=useState(0);const [entering,setEntering]=useState(false);const [progress,setProgress]=useState(0);
useEffect(()=>{let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const p=Math.max(0,Math.min(4,window.scrollY/window.innerHeight));setProgress(p);setStep(Math.min(4,Math.floor(p+.35)))})};window.addEventListener("scroll",update,{passive:true});update();return()=>{cancelAnimationFrame(frame);window.removeEventListener("scroll",update)}},[]);
const enter=()=>{if(entering)return;setEntering(true);setTimeout(onEnter,matchMedia("(prefers-reduced-motion: reduce)").matches?0:850)};
const go=(i:number)=>window.scrollTo({top:i*innerHeight,behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth"});
return <main className={`landing ${entering?"entering":""}`}><div className="story-stage" data-step={step}>
<header className="landing-header"><a href="#" className="wordmark" aria-label="Aura, início" onClick={e=>{e.preventDefault();go(0)}}><span className="brand-glyph">◌</span>AURA<span className="brand-ia">IA</span></a><nav aria-label="Navegação principal"><button className={step<2?"active":""} onClick={()=>go(1)}>A experiência</button><button className={step===3?"active":""} onClick={()=>go(3)}>Possibilidades</button></nav><button className="header-enter" onClick={enter}>Entrar na Aura <ArrowUpRight size={16}/></button></header>
<div className="ambient-grid" aria-hidden="true"/><div className="coordinates left-coordinate">UM ESPAÇO PARA O QUE AINDA NÃO EXISTE.</div><div className="coordinates right-coordinate">HUMANO + INTELIGÊNCIA</div>
<div className="story-content" key={step}>
{step===0?<><div className="hero-overline"><span/> UMA NOVA FORMA DE PENSAR JUNTO</div><h1>Uma presença.<br/><span>Infinitas possibilidades.</span></h1><p className="hero-sub">Inteligência que conversa com você.</p></>:<div className="chapter-heading"><p className="eyebrow">0{step+1} / {chapters[step]}</p><h1>{["","Converse naturalmente.","Ou simplesmente fale.","Pergunte. Crie. Descubra.","Sua Aura está pronta."][step]}</h1><p className="hero-sub">{["","Uma pergunta pode ser o começo de algo extraordinário.","Menos distância entre o que você pensa e o que você diz.","Dê espaço à sua curiosidade.","Toda grande ideia começa com uma conversa."][step]}</p></div>}
</div>
<div className={`core-stage core-step-${step}`}><AuraCore state={step===2?"LISTENING":"IDLE"} level={step===2?.28:0}/>{step===0&&<div className="core-caption">A U R A <span>INTELIGÊNCIA EM MOVIMENTO</span></div>}{step===2&&<div className="voice-demo"><AudioLines size={22}/><span>Uma conversa. Sem barreiras.</span></div>}{step===3&&<div className="capability-orbit">{["Escrever","Programar","Pesquisar","Explicar","Criar ideias","Analisar"].map((x,i)=><button key={x} className={`capability cap-${i}`} onClick={enter}><Plus size={12}/>{x}</button>)}</div>}</div>
{step===1&&<div className="conversation-demo"><div className="demo-user">E se a gente começasse com uma ideia?</div><p className="eyebrow">AURA</p><p>Então vamos dar forma a ela.<br/><span>O que você está imaginando?</span></p><span className="typing-dot"/></div>}
<div className="hero-bottom">{step===0?<><button className="primary-button" onClick={enter}>Conheça sua Aura <ArrowUpRight size={17}/></button><span className="under-button">Sua próxima ideia começa aqui.</span></>:step===4?<button className="primary-button" onClick={enter}>Começar conversa <ArrowRight size={17}/></button>:<button className="text-button" onClick={()=>go(step+1)}>Continue explorando <ArrowDown size={15}/></button>}</div>
<footer className="landing-footer"><button className="scroll-cue" onClick={()=>go(Math.min(4,step+1))}><span className="scroll-line"/><span>{step===0?"ROLE PARA CONHECER":"EXPLORE A EXPERIÊNCIA"}</span></button><div className="chapter-nav" aria-label="Etapas da experiência">{chapters.map((x,i)=><button key={x} aria-label={x} aria-current={i===step?"step":undefined} onClick={()=>go(i)}><span className={step===i?"selected":""}/></button>)}<span>0{step+1}<span className="dim"> / 05</span></span></div><span className="footer-note">Feita para pensar com você.</span></footer><div className="story-progress" style={{transform:`scaleX(${progress/4})`}}/>
</div></main>}
